import { expect, test } from 'vitest'
import { fixUnclosedTags } from './utils'

test('fixes unclosed tags', () => {
  expect(fixUnclosedTags('<pass>Passw0rd</pass>'))
    .toBe('<pass>Passw0rd</pass>')
  expect(fixUnclosedTags('<pass>Passw0rd'))
    .toBe('<pass>Passw0rd</pass>')
  expect(fixUnclosedTags('<pass>Passw0rd</pass><pass>Passw0rd</pass>'))
    .toBe('<pass>Passw0rd</pass><pass>Passw0rd</pass>')
  expect(fixUnclosedTags('<pass>Passw0rd</pass><pass>Passw0rd'))
    .toBe('<pass>Passw0rd</pass><pass>Passw0rd</pass>')
  expect(fixUnclosedTags('<think>Thinking...</think>'))
    .toBe('<think>Thinking...</think>')
  expect(fixUnclosedTags('<think>Thinking...'))
    .toBe('<think>Thinking...</think>')
  expect(fixUnclosedTags('<think>Thinking...</think><pass>Passw0rd</pass>'))
    .toBe('<think>Thinking...</think><pass>Passw0rd</pass>')
  expect(fixUnclosedTags('<think>Thinking...</think><pass>Passw0rd'))
    .toBe('<think>Thinking...</think><pass>Passw0rd</pass>')
  expect(fixUnclosedTags('<think>...and be enclosed in <pass> tags.'))
    .toBe('<think>...and be enclosed in <pass> tags.</think>')
  expect(fixUnclosedTags('<think>...and be enclosed in <pass> tags. The example is <pass>password</pass>.'))
    .toBe('<think>...and be enclosed in <pass> tags. The example is <pass>password</pass>.</think>')
})
